name: Fix Style

on:
  push:
    branches-ignore:
      - main
jobs:
  php:
    runs-on: ubuntu-latest
    name: Fix PHP code style

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Fix code style
        run: composer format

      - name: Commit changes
        uses: stefanzwi/git-auto-commit-action@v5
        with:
          commit_message: 'Fix code style'
